### ISSUE TITLE
Add Items to Editable List via Script? 

### ISSUE THREAD

**Issue by jdbodyfelt** [upgradeQ/OBS-Studio-Python-Scripting-Cheatsheet-obspython-Examples-of-API#11]
Hi upgradeQ - first off thank you VERY much for your great tutorial/cheatsheet - it has helped me wrap my head around the various OBS objects. I have a question you might be able to answer - let me first setup the problem. I have a string list stored programmatically (e.g. from a pandas dataframe), let's say `list_items = ["Item 1", "Item 2", "Item 3"]`. I noticed that the regular list/combo-box has the function `obs_obs_property_list_add_string(obs_property_t *p, const char *name, const char *val)` to insert items. My question is if you are familiar with how to do likewise for the editable list? I can't find much in the documentation regarding this. Thank you for your help and advice!

**Comment by upgradeQ** [comment]
Hello @jdbodyfelt , I've not yet used [`obs_properties_add_editable_list`](https://obsproject.com/docs/reference-properties.html#c.obs_properties_add_editable_list) , however there is a lot of API usage examples [here](https://github.com/search?l=Python&q=obs_properties_add_editable_list&type=Code).

**Comment by jdbodyfelt** [comment]
Sweet! Thanks for that link! Sure I can dig something out from it. Currently, making end users edit their own CSVs and just loading to a disabled multiline text. Dirty, but it works.
