### ISSUE TITLE
Retrieve a obs_source_info from a obs_source_t?

### ISSUE THREAD

**Issue by ggregoire** [upgradeQ/OBS-Studio-Python-Scripting-Cheatsheet-obspython-Examples-of-API#30]
Hi!

I was wondering if you could maybe help me with this.

I'm trying to retrieve a `obs_source_info` from a `obs_source_t` but can't figure how to. Both types are documented [on the same page](https://obsproject.com/docs/reference-sources.html) so I guess they are related. I can't access the `obs_source_info`'s attributes directly on `obs_source_t` (i.e. `AttributeError: 'SwigPyObject' object has no attribute '…'`) but I can't find any method like `get_source_info` either.

Here is the code I have so far.

I retrieve the source of a scene item (i.e. `obs_source_t`) and I'd would like to get its `obs_source_info`:

```python
import obspython as obs

current_scene = obs.obs_frontend_get_current_scene() 

print("current_scene", current_scene) # <Swig Object of type 'obs_source_t *' at 0x12...>

if current_scene:
    scene = obs.obs_scene_from_source(current_scene)
    scene_item = obs.obs_scene_find_source(scene, "stream_source")

    print("scene_item", scene_item) # <Swig Object of type 'obs_sceneitem_t *' at 0x12...>

    if scene_item:
        source = obs.obs_sceneitem_get_source(scene_item)

        print("source", source) # <Swig Object of type 'obs_source_t *' at 0x12...>
        print("source media_get_time", source.media_get_time)  # AttributeError: 'SwigPyObject' object has no attribute 'media_get_time'

		# How to get a obs_source_info then?

        obs.obs_source_release(source)

    obs.obs_source_release(current_scene)
```

Thanks!

**Comment by MarioMey** [comment]
Try `sourceSettings = obs.obs_source_get_settings(source)`. Maybe, you have to do something like this (code is only to guide you):

```py
source_name = 'something.mp4'
source = obs.obs_get_source_by_name(source_name)
sourceSettings = obs.obs_source_get_settings(source)
newSettings = obs.obs_data_create()

# These can or not be
# obs.obs_data_set_string(newSettings, "sourceName", obs.obs_source_get_name(source))
# obs.obs_data_set_string(newSettings, "sourceId", obs.obs_source_get_id(source))
# obs.obs_data_set_double(newSettings, "sourceType", obs.obs_source_get_type(source))
obs.obs_data_set_obj(newSettings, "sourceSettings", sourceSettings)
retorno = obs.obs_data_get_json(newSettings)
print(retorno)

obs.obs_source_release(source)
obs.obs_data_release(newSettings)
```

**Comment by upgradeQ** [comment]
There are rough edges regarding SWIG usage, see [this](https://github.com/obsproject/obs-studio/wiki/Getting-Started-With-OBS-Scripting#bindings) and [this](https://github.com/obsproject/obs-studio/issues/3462). One workaround is to use FFI. 
Alternative solution to your code, would be using [`obs_source_media_get_time`](https://github.com/obsproject/obs-studio/search?q=obs_source_media_get_time) . Note, some functions are not documented in the sphinx docs, for that use auto generated from `obspython`  [`export.md`](https://github.com/upgradeQ/OBS-Studio-Python-Scripting-Cheatsheet-obspython-Examples-of-API/blob/master/src/export.md) document and <kbd> Ctrl + f</kbd>

**Comment by ggregoire** [comment]
> There are rough edges regarding SWIG usage, see [this](https://github.com/obsproject/obs-studio/wiki/Getting-Started-With-OBS-Scripting#bindings) and [this](https://github.com/obsproject/obs-studio/issues/3462). One workaround is to use FFI. Alternative solution to your code, would be using [`obs_source_media_get_time`](https://github.com/obsproject/obs-studio/search?q=obs_source_media_get_time) . Note, some functions are not documented in the sphinx docs, for that use auto generated from `obspython` [`export.md`](https://github.com/upgradeQ/OBS-Studio-Python-Scripting-Cheatsheet-obspython-Examples-of-API/blob/master/src/export.md?rgh-link-date=2022-01-23T02%3A22%3A17Z) document and Ctrl + f

@upgradeQ Thank you! I just tested `obs_source_media_get_time(source)` and it works as expected!
