### ISSUE TITLE
there is not source file when i am reading chapter `Timing (sequential primitives) ` in  readme.md  

### ISSUE THREAD

**Issue by Kevin-Kevin** [upgradeQ/OBS-Studio-Python-Scripting-Cheatsheet-obspython-Examples-of-API#35]
the opened page said:
 The master branch of OBS-Studio-Python-Scripting-Cheatsheet-obspython-Examples-of-API does not contain the path src/example_class.py.

**Comment by upgradeQ** [comment]
Thanks, I fixed the link, the source file was in git [history](https://github.com/upgradeQ/OBS-Studio-Python-Scripting-Cheatsheet-obspython-Examples-of-API/blob/cd2861b6b0a8e153e3483fdbda1c818b9e58a378/src/example_class.py)
